# Generated by Django 3.0.6 on 2020-05-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0003_dairy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dairy',
            new_name='Diary',
        ),
    ]
