# Generated by Django 3.0.6 on 2020-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0004_auto_20200523_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.IntegerField(),
        ),
    ]
